name: ci
on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"
jobs:
  build-test:
    name: "Build and test"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.MACHINEUSER_PRIVATE_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install wasm-pack
        run: yarn global add wasm-pack
      - name: Install project dependencies
        run: yarn install --frozen-lockfile
      - name: Build packages
        # TODO: See if we can update to using lerna in the future (getting error atm)
        run: |
          yarn workspace @contentauth/detector build
          yarn workspace @contentauth/toolkit build
          yarn workspace c2pa build
          yarn workspace @contentauth/react-hooks build
          yarn workspace c2pa-wc build
      - name: Run integration tests
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: yarn test:ci
      - name: Run example tests
        run: |
          yarn workspace c2pa link
          yarn workspace @contentauth/toolkit link
          pushd examples/minimal-ts-vite
          yarn install
          yarn link c2pa @contentauth/toolkit
          yarn test
          popd
      - name: Create build archive
        run: |
          tar cvfz build.tar.gz \
          --exclude=.git \
          --exclude=node_modules \
          --exclude=examples \
          --exclude=docs \
          --exclude=target \
          --exclude=tests \
          packages *.json *.md LICENSE
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ github.run_id }}
          path: build.tar.gz
          retention-days: 7
